# Generated by Django 5.1.5 on 2026-05-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PlatformAdmin', 'Platform Admin'), ('OrganisationAdmin', 'Organisation Admin'), ('Receptionist', 'Receptionist'), ('Employee', 'Employee'), ('External', 'External')], default='Employee', max_length=20),
        ),
    ]
