# Generated by Django 5.1.5 on 2026-04-20 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='The organisation this user belongs to. Leave blank for Platform Admins.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PlatformAdmin', 'Platform Admin'), ('OrganisationAdmin', 'Organisation Admin'), ('Receptionist', 'Receptionist'), ('Employee', 'Employee'), ('External', 'External')], default='Employee', max_length=20),
        ),
    ]
