# Generated by Django 5.1.5 on 2026-05-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_organisation_user_phone_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PlatformAdmin', 'Platform Admin'), ('OrganisationAdmin', 'Organisation Admin'), ('Receptionist', 'Receptionist'), ('Employee', 'Employee'), ('External', 'External')], default='External', max_length=20),
        ),
    ]
