[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "DJANGO_SETTINGS_MODULE=config.settings.production python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
