# Generated by Django 5.1.5 on 2026-04-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organisation_logos/'),
        ),
    ]
