# Generated by Django 5.1.5 on 2026-05-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organisationapplication_applicationresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationresource',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo of the resource (JPEG, PNG, WebP — max 5 MB)', null=True, upload_to='application_resources/'),
        ),
    ]
