# Generated by Django 5.1.5 on 2026-05-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organisationapplication_applicationresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
