# Generated by Django 5.1.5 on 2026-05-27 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_applicationresource_image_organisation_approved_at_and_more'),
        ('core', '0003_organisation_approved_at_organisation_is_approved'),
    ]

    operations = [
    ]
