# Generated by Django 5.1.5 on 2026-05-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_core_0004s'),
        ('core', '0005_applicationresource_db_image'),
    ]

    operations = []
