# Generated by Django 5.1.5 on 2026-05-08 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['resource', 'start_time', 'end_time'], name='bookings_bo_resourc_fe19bd_idx'),
        ),
    ]
