# Generated by Django 5.1.5 on 2026-05-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_paid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Booked', max_length=20),
        ),
    ]
