# Generated by Django 5.1.5 on 2026-05-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_simplify_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Issued', 'Issued'), ('Verified', 'Verified'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('no_show', 'No Show')], default='Booked', max_length=20),
        ),
    ]
