# Generated by Django 5.1.5 on 2026-05-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_status'),
        ('bookings', '0007_restore_pending_status'),
    ]

    operations = [
    ]
