# Generated by Django 5.1.5 on 2026-05-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_merge_20260528_0057'),
        ('bookings', '0008_merge_20260528_0159'),
    ]

    operations = [
    ]
