# Generated by Django 5.1.5 on 2026-05-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='photo_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='photo_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
