# Generated by Django 5.1.5 on 2026-05-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_image_url'),
        ('resources', '0003_resource_photo_url'),
    ]

    operations = [
    ]
