# Generated by Django 5.1.5 on 2026-05-27 21:19

from django.db import migrations, models


def add_resource_is_active(apps, schema_editor):
    Resource = apps.get_model('resources', 'Resource')
    table = Resource._meta.db_table
    existing_columns = {
        column.name for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(),
            table,
        )
    }

    if 'is_active' not in existing_columns:
        field = models.BooleanField(default=False)
        field.set_attributes_from_name('is_active')
        schema_editor.add_field(Resource, field)


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_merge_0002_resource_image_url_0003_resource_photo_url'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_resource_is_active,
                    migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='resource',
                    name='is_active',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='image_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
