# Generated by Django 5.1.5 on 2026-05-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_merge_0002_resource_image_url_0003_resource_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
