# Generated by Django 5.1.5 on 2026-05-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_resource_image_url'),
        ('resources', '0005_resource_is_active'),
        ('resources', '0006_activate_existing_resources'),
    ]

    operations = [
    ]
