# Generated by Django 5.1.5 on 2026-05-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_merge_20260528_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
