# Generated by Django 5.1.5 on 2026-05-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_resource_is_active'),
        ('resources', '0008_resource_db_photo_fields'),
    ]

    operations = [
    ]
